declare module Resources {
    export var Action_Create: string;
    export var Information_YouCantHaveMoreThanOne: string;
    export var Information_SubmittingFeedback: string;
    export var Information_ThanksForFeedback: string;
    export var Error_SubmittingFeedback: string;
    export var Information_LogicApp: string;
    export var Information_WebApp: string;
    export var Information_APIApp: string;
    export var Information_MobileApp: string;
    export var Action_SelectAppType: string;
    export var Action_SelectTemplate: string;
    export var Action_GenericWorkWithYourApp: string;
    export var Information_ComingSoon: string;
    export var Information_DownloadClient: string;
    export var Information_SelectTemplate: string;
    export var Information_LogicAppDescription: string;
    export var Information_LogicAppStep1: string;
    export var Information_LogicAppStep2: string;
    export var Information_WebAppDescription: string;
    export var Information_MobileAppDescription: string;
    export var Information_ApiAppDescription: string;
    export var Templates_PingSiteDescription: string;
}